### ISSUE TITLE
after 19-III commit.

### ISSUE THREAD

**Issue by Wolvverine** [pavlovdo/pystormon#16]
# /usr/lib/zabbix/externalscripts/pystormon/storage_objects_discovery.py
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'NetworkDevice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/pystormon/storage_objects_discovery.py", line 17, in <module>
    from functions import slack_post, zabbix_send
  File "/usr/lib/zabbix/externalscripts/pystormon/functions.py", line 20, in <module>
    'slack_hook', 'zabbix_server')
  File "/usr/lib/zabbix/externalscripts/pystormon/configread.py", line 18, in configread
    params[parameter] = config.get(section, parameter)
  File "/usr/lib64/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'NetworkDevice'

**Comment by Wolvverine** [comment]
the pystormon.conf is in {project}\conf.d directory not {project}\, but script search in  {project}\

**Comment by pavlovdo** [comment]
Thank you for this issue, fixed.
